version: '3.9'
services:
  api:
    build: .
    ports:
      - "9000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: dev

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "9005:3005"
    volumes:
      - .:/test
    environment:
      NODE_ENV: test